//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ContactMethod.
const (
	ContactMethodEmail     ContactMethod = "email"
	ContactMethodInstagram ContactMethod = "instagram"
	ContactMethodOther     ContactMethod = "other"
	ContactMethodPhone     ContactMethod = "phone"
	ContactMethodWhatsapp  ContactMethod = "whatsapp"
)

// Defines values for DemoLoginResponseTokenType.
const (
	Bearer DemoLoginResponseTokenType = "Bearer"
)

// Defines values for DonationStatus.
const (
	DonationStatusAvailable       DonationStatus = "available"
	DonationStatusCanceled        DonationStatus = "canceled"
	DonationStatusDelivered       DonationStatus = "delivered"
	DonationStatusPickedUp        DonationStatus = "picked_up"
	DonationStatusPickupAssigned  DonationStatus = "pickup_assigned"
	DonationStatusProposalPending DonationStatus = "proposal_pending"
)

// Defines values for EntityType.
const (
	EntityTypeCharity    EntityType = "charity"
	EntityTypeFamily     EntityType = "family"
	EntityTypeIndividual EntityType = "individual"
	EntityTypeOrphanage  EntityType = "orphanage"
	EntityTypeOther      EntityType = "other"
	EntityTypeRestaurant EntityType = "restaurant"
	EntityTypeShelter    EntityType = "shelter"
	EntityTypeWarteg     EntityType = "warteg"
)

// Defines values for NotificationType.
const (
	NotificationTypeDonationCreated  NotificationType = "donation_created"
	NotificationTypePickupAssigned   NotificationType = "pickup_assigned"
	NotificationTypePickupCompleted  NotificationType = "pickup_completed"
	NotificationTypeProposalAccepted NotificationType = "proposal_accepted"
	NotificationTypeProposalCreated  NotificationType = "proposal_created"
	NotificationTypeProposalRejected NotificationType = "proposal_rejected"
)

// Defines values for PickupStatus.
const (
	PickupStatusAssigned  PickupStatus = "assigned"
	PickupStatusCanceled  PickupStatus = "canceled"
	PickupStatusDelivered PickupStatus = "delivered"
	PickupStatusPickedUp  PickupStatus = "picked_up"
)

// Defines values for ProposalStatus.
const (
	ProposalStatusAccepted ProposalStatus = "accepted"
	ProposalStatusCanceled ProposalStatus = "canceled"
	ProposalStatusPending  ProposalStatus = "pending"
	ProposalStatusRejected ProposalStatus = "rejected"
)

// Defines values for UserRole.
const (
	Donor     UserRole = "donor"
	Receiver  UserRole = "receiver"
	Volunteer UserRole = "volunteer"
)

// ContactMethod defines model for ContactMethod.
type ContactMethod string

// CreateDeliveryProposalRequest defines model for CreateDeliveryProposalRequest.
type CreateDeliveryProposalRequest struct {
	DonationId string `json:"donationId"`
	ReceiverId string `json:"receiverId"`
}

// CreateDonationRequest defines model for CreateDonationRequest.
type CreateDonationRequest struct {
	AvailableFrom       time.Time `json:"availableFrom"`
	AvailableUntil      time.Time `json:"availableUntil"`
	Description         string    `json:"description"`
	ImageUrl            *string   `json:"imageUrl,omitempty"`
	PickupLocation      Location  `json:"pickupLocation"`
	Quantity            string    `json:"quantity"`
	SpecialInstructions *string   `json:"specialInstructions,omitempty"`
	Title               string    `json:"title"`
}

// DeliveryProposal defines model for DeliveryProposal.
type DeliveryProposal struct {
	CreatedAt          time.Time      `json:"createdAt"`
	DonationId         string         `json:"donationId"`
	DonorAcceptedAt    *time.Time     `json:"donorAcceptedAt,omitempty"`
	Id                 string         `json:"id"`
	ReceiverAcceptedAt *time.Time     `json:"receiverAcceptedAt,omitempty"`
	ReceiverId         string         `json:"receiverId"`
	RejectedByUserId   *string        `json:"rejectedByUserId,omitempty"`
	Status             ProposalStatus `json:"status"`
	UpdatedAt          time.Time      `json:"updatedAt"`
	VolunteerId        string         `json:"volunteerId"`
}

// DeliveryProposalAcceptResponse defines model for DeliveryProposalAcceptResponse.
type DeliveryProposalAcceptResponse struct {
	Pickup   *Pickup          `json:"pickup,omitempty"`
	Proposal DeliveryProposal `json:"proposal"`
}

// DeliveryProposalListResponse defines model for DeliveryProposalListResponse.
type DeliveryProposalListResponse struct {
	Items    []DeliveryProposal `json:"items"`
	Page     int                `json:"page"`
	PageSize int                `json:"pageSize"`
	Total    int                `json:"total"`
}

// DemoLoginRequest defines model for DemoLoginRequest.
type DemoLoginRequest struct {
	Role   *UserRole `json:"role,omitempty"`
	UserId *string   `json:"userId,omitempty"`
}

// DemoLoginResponse defines model for DemoLoginResponse.
type DemoLoginResponse struct {
	AccessToken string                      `json:"accessToken"`
	TokenType   *DemoLoginResponseTokenType `json:"tokenType,omitempty"`
	User        User                        `json:"user"`
}

// DemoLoginResponseTokenType defines model for DemoLoginResponse.TokenType.
type DemoLoginResponseTokenType string

// Donation defines model for Donation.
type Donation struct {
	AvailableFrom       time.Time      `json:"availableFrom"`
	AvailableUntil      time.Time      `json:"availableUntil"`
	CreatedAt           time.Time      `json:"createdAt"`
	Description         string         `json:"description"`
	DonorId             string         `json:"donorId"`
	Id                  string         `json:"id"`
	ImageUrl            *string        `json:"imageUrl,omitempty"`
	PickupLocation      Location       `json:"pickupLocation"`
	Quantity            string         `json:"quantity"`
	SpecialInstructions *string        `json:"specialInstructions,omitempty"`
	Status              DonationStatus `json:"status"`
	Title               string         `json:"title"`
	UpdatedAt           time.Time      `json:"updatedAt"`
}

// DonationListResponse defines model for DonationListResponse.
type DonationListResponse struct {
	Items    []Donation `json:"items"`
	Page     int        `json:"page"`
	PageSize int        `json:"pageSize"`
	Total    int        `json:"total"`
}

// DonationStatus defines model for DonationStatus.
type DonationStatus string

// EntityType defines model for EntityType.
type EntityType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Location defines model for Location.
type Location struct {
	AddressLine1 string   `json:"addressLine1"`
	AddressLine2 *string  `json:"addressLine2,omitempty"`
	City         string   `json:"city"`
	Country      string   `json:"country"`
	Latitude     *float64 `json:"latitude,omitempty"`
	Longitude    *float64 `json:"longitude,omitempty"`
	PostalCode   string   `json:"postalCode"`
	Region       string   `json:"region"`
}

// Notification defines model for Notification.
type Notification struct {
	Body       string           `json:"body"`
	CreatedAt  time.Time        `json:"createdAt"`
	DonationId *string          `json:"donationId,omitempty"`
	Id         string           `json:"id"`
	PickupId   *string          `json:"pickupId,omitempty"`
	ProposalId *string          `json:"proposalId,omitempty"`
	Read       bool             `json:"read"`
	ReadAt     *time.Time       `json:"readAt,omitempty"`
	Title      string           `json:"title"`
	Type       NotificationType `json:"type"`
	UserId     string           `json:"userId"`
}

// NotificationListResponse defines model for NotificationListResponse.
type NotificationListResponse struct {
	Items    []Notification `json:"items"`
	Page     int            `json:"page"`
	PageSize int            `json:"pageSize"`
	Total    int            `json:"total"`
}

// NotificationType defines model for NotificationType.
type NotificationType string

// Pickup defines model for Pickup.
type Pickup struct {
	CreatedAt        time.Time    `json:"createdAt"`
	DeliveredAt      *time.Time   `json:"deliveredAt,omitempty"`
	DeliveryLocation Location     `json:"deliveryLocation"`
	DonationId       string       `json:"donationId"`
	Id               string       `json:"id"`
	PickedUpAt       *time.Time   `json:"pickedUpAt,omitempty"`
	PickupLocation   Location     `json:"pickupLocation"`
	ProposalId       string       `json:"proposalId"`
	ReceiverId       string       `json:"receiverId"`
	Status           PickupStatus `json:"status"`
	UpdatedAt        time.Time    `json:"updatedAt"`
	VolunteerId      string       `json:"volunteerId"`
}

// PickupStatus defines model for PickupStatus.
type PickupStatus string

// Profile defines model for Profile.
type Profile struct {
	ContactMethod    ContactMethod `json:"contactMethod"`
	ContactValue     string        `json:"contactValue"`
	CreatedAt        time.Time     `json:"createdAt"`
	DisplayName      string        `json:"displayName"`
	EntityType       *EntityType   `json:"entityType,omitempty"`
	Location         Location      `json:"location"`
	Notes            *string       `json:"notes,omitempty"`
	OperationalHours *string       `json:"operationalHours,omitempty"`
	Role             UserRole      `json:"role"`
	UpdatedAt        time.Time     `json:"updatedAt"`
	UserId           string        `json:"userId"`
}

// ProfileListResponse defines model for ProfileListResponse.
type ProfileListResponse struct {
	Items    []Profile `json:"items"`
	Page     int       `json:"page"`
	PageSize int       `json:"pageSize"`
	Total    int       `json:"total"`
}

// ProposalStatus defines model for ProposalStatus.
type ProposalStatus string

// UpdatePickupStatusRequest defines model for UpdatePickupStatusRequest.
type UpdatePickupStatusRequest struct {
	OccurredAt *time.Time `json:"occurredAt,omitempty"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	ContactMethod    ContactMethod `json:"contactMethod"`
	ContactValue     string        `json:"contactValue"`
	DisplayName      string        `json:"displayName"`
	EntityType       *EntityType   `json:"entityType,omitempty"`
	Location         Location      `json:"location"`
	Notes            *string       `json:"notes,omitempty"`
	OperationalHours *string       `json:"operationalHours,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`
	Id        string              `json:"id"`
	Name      string              `json:"name"`
	Phone     *string             `json:"phone,omitempty"`
	Role      UserRole            `json:"role"`
}

// UserRole defines model for UserRole.
type UserRole string

// Id defines model for Id.
type Id = string

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListDeliveryProposalsParams defines parameters for ListDeliveryProposals.
type ListDeliveryProposalsParams struct {
	Page     *Page           `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize       `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	Status   *ProposalStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListDonationsParams defines parameters for ListDonations.
type ListDonationsParams struct {
	Page     *Page           `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize       `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	Status   *DonationStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListNotificationsParams defines parameters for ListNotifications.
type ListNotificationsParams struct {
	Page     *Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListReceiversParams defines parameters for ListReceivers.
type ListReceiversParams struct {
	Page     *Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// DemoLoginJSONRequestBody defines body for DemoLogin for application/json ContentType.
type DemoLoginJSONRequestBody = DemoLoginRequest

// CreateDeliveryProposalJSONRequestBody defines body for CreateDeliveryProposal for application/json ContentType.
type CreateDeliveryProposalJSONRequestBody = CreateDeliveryProposalRequest

// CreateDonationJSONRequestBody defines body for CreateDonation for application/json ContentType.
type CreateDonationJSONRequestBody = CreateDonationRequest

// UpdateMyProfileJSONRequestBody defines body for UpdateMyProfile for application/json ContentType.
type UpdateMyProfileJSONRequestBody = UpdateProfileRequest

// MarkPickupDeliveredJSONRequestBody defines body for MarkPickupDelivered for application/json ContentType.
type MarkPickupDeliveredJSONRequestBody = UpdatePickupStatusRequest

// MarkPickupPickedUpJSONRequestBody defines body for MarkPickupPickedUp for application/json ContentType.
type MarkPickupPickedUpJSONRequestBody = UpdatePickupStatusRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Log in as a seeded demo user.
	// (POST /auth/demo-login)
	DemoLogin(w http.ResponseWriter, r *http.Request)
	// List delivery proposals visible to current role.
	// (GET /delivery-proposals)
	ListDeliveryProposals(w http.ResponseWriter, r *http.Request, params ListDeliveryProposalsParams)
	// Create a delivery proposal. Volunteer only.
	// (POST /delivery-proposals)
	CreateDeliveryProposal(w http.ResponseWriter, r *http.Request)
	// Accept delivery proposal as donor or receiver.
	// (POST /delivery-proposals/{id}/accept)
	AcceptDeliveryProposal(w http.ResponseWriter, r *http.Request, id Id)
	// Reject delivery proposal as donor or receiver.
	// (POST /delivery-proposals/{id}/reject)
	RejectDeliveryProposal(w http.ResponseWriter, r *http.Request, id Id)
	// List donations visible to current role.
	// (GET /donations)
	ListDonations(w http.ResponseWriter, r *http.Request, params ListDonationsParams)
	// Create a donation. Donor only.
	// (POST /donations)
	CreateDonation(w http.ResponseWriter, r *http.Request)
	// Get donation by ID.
	// (GET /donations/{id})
	GetDonation(w http.ResponseWriter, r *http.Request, id Id)
	// Get current authenticated user.
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Get current user's profile.
	// (GET /me/profile)
	GetMyProfile(w http.ResponseWriter, r *http.Request)
	// Update current user's profile.
	// (PUT /me/profile)
	UpdateMyProfile(w http.ResponseWriter, r *http.Request)
	// List notifications.
	// (GET /notifications)
	ListNotifications(w http.ResponseWriter, r *http.Request, params ListNotificationsParams)
	// Stream current notifications as Server-Sent Events.
	// (GET /notifications/stream)
	StreamNotifications(w http.ResponseWriter, r *http.Request)
	// Mark notification read.
	// (POST /notifications/{id}/read)
	MarkNotificationRead(w http.ResponseWriter, r *http.Request, id Id)
	// Mark pickup as delivered. Assigned volunteer only.
	// (POST /pickups/{id}/deliver)
	MarkPickupDelivered(w http.ResponseWriter, r *http.Request, id Id)
	// Mark pickup as picked up. Assigned volunteer only.
	// (POST /pickups/{id}/pickup)
	MarkPickupPickedUp(w http.ResponseWriter, r *http.Request, id Id)
	// List receiver profiles. Volunteer only.
	// (GET /receivers)
	ListReceivers(w http.ResponseWriter, r *http.Request, params ListReceiversParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DemoLogin operation middleware
func (siw *ServerInterfaceWrapper) DemoLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DemoLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDeliveryProposals operation middleware
func (siw *ServerInterfaceWrapper) ListDeliveryProposals(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDeliveryProposalsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeliveryProposals(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDeliveryProposal operation middleware
func (siw *ServerInterfaceWrapper) CreateDeliveryProposal(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDeliveryProposal(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptDeliveryProposal operation middleware
func (siw *ServerInterfaceWrapper) AcceptDeliveryProposal(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptDeliveryProposal(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectDeliveryProposal operation middleware
func (siw *ServerInterfaceWrapper) RejectDeliveryProposal(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectDeliveryProposal(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDonations operation middleware
func (siw *ServerInterfaceWrapper) ListDonations(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDonationsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDonations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDonation operation middleware
func (siw *ServerInterfaceWrapper) CreateDonation(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDonation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDonation operation middleware
func (siw *ServerInterfaceWrapper) GetDonation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDonation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyProfile operation middleware
func (siw *ServerInterfaceWrapper) GetMyProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMyProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateMyProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMyProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNotifications operation middleware
func (siw *ServerInterfaceWrapper) ListNotifications(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNotificationsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNotifications(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamNotifications operation middleware
func (siw *ServerInterfaceWrapper) StreamNotifications(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamNotifications(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkNotificationRead operation middleware
func (siw *ServerInterfaceWrapper) MarkNotificationRead(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkNotificationRead(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkPickupDelivered operation middleware
func (siw *ServerInterfaceWrapper) MarkPickupDelivered(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkPickupDelivered(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkPickupPickedUp operation middleware
func (siw *ServerInterfaceWrapper) MarkPickupPickedUp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkPickupPickedUp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListReceivers operation middleware
func (siw *ServerInterfaceWrapper) ListReceivers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReceiversParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListReceivers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/auth/demo-login", wrapper.DemoLogin)
	m.HandleFunc("GET "+options.BaseURL+"/delivery-proposals", wrapper.ListDeliveryProposals)
	m.HandleFunc("POST "+options.BaseURL+"/delivery-proposals", wrapper.CreateDeliveryProposal)
	m.HandleFunc("POST "+options.BaseURL+"/delivery-proposals/{id}/accept", wrapper.AcceptDeliveryProposal)
	m.HandleFunc("POST "+options.BaseURL+"/delivery-proposals/{id}/reject", wrapper.RejectDeliveryProposal)
	m.HandleFunc("GET "+options.BaseURL+"/donations", wrapper.ListDonations)
	m.HandleFunc("POST "+options.BaseURL+"/donations", wrapper.CreateDonation)
	m.HandleFunc("GET "+options.BaseURL+"/donations/{id}", wrapper.GetDonation)
	m.HandleFunc("GET "+options.BaseURL+"/me", wrapper.GetMe)
	m.HandleFunc("GET "+options.BaseURL+"/me/profile", wrapper.GetMyProfile)
	m.HandleFunc("PUT "+options.BaseURL+"/me/profile", wrapper.UpdateMyProfile)
	m.HandleFunc("GET "+options.BaseURL+"/notifications", wrapper.ListNotifications)
	m.HandleFunc("GET "+options.BaseURL+"/notifications/stream", wrapper.StreamNotifications)
	m.HandleFunc("POST "+options.BaseURL+"/notifications/{id}/read", wrapper.MarkNotificationRead)
	m.HandleFunc("POST "+options.BaseURL+"/pickups/{id}/deliver", wrapper.MarkPickupDelivered)
	m.HandleFunc("POST "+options.BaseURL+"/pickups/{id}/pickup", wrapper.MarkPickupPickedUp)
	m.HandleFunc("GET "+options.BaseURL+"/receivers", wrapper.ListReceivers)

	return m
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type DemoLoginRequestObject struct {
	Body *DemoLoginJSONRequestBody
}

type DemoLoginResponseObject interface {
	VisitDemoLoginResponse(w http.ResponseWriter) error
}

type DemoLogin200JSONResponse DemoLoginResponse

func (response DemoLogin200JSONResponse) VisitDemoLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DemoLogin400JSONResponse struct{ BadRequestJSONResponse }

func (response DemoLogin400JSONResponse) VisitDemoLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DemoLogin500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DemoLogin500JSONResponse) VisitDemoLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListDeliveryProposalsRequestObject struct {
	Params ListDeliveryProposalsParams
}

type ListDeliveryProposalsResponseObject interface {
	VisitListDeliveryProposalsResponse(w http.ResponseWriter) error
}

type ListDeliveryProposals200JSONResponse DeliveryProposalListResponse

func (response ListDeliveryProposals200JSONResponse) VisitListDeliveryProposalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListDeliveryProposals400JSONResponse struct{ BadRequestJSONResponse }

func (response ListDeliveryProposals400JSONResponse) VisitListDeliveryProposalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListDeliveryProposals401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListDeliveryProposals401JSONResponse) VisitListDeliveryProposalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListDeliveryProposals500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListDeliveryProposals500JSONResponse) VisitListDeliveryProposalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeliveryProposalRequestObject struct {
	Body *CreateDeliveryProposalJSONRequestBody
}

type CreateDeliveryProposalResponseObject interface {
	VisitCreateDeliveryProposalResponse(w http.ResponseWriter) error
}

type CreateDeliveryProposal201JSONResponse DeliveryProposal

func (response CreateDeliveryProposal201JSONResponse) VisitCreateDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeliveryProposal400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateDeliveryProposal400JSONResponse) VisitCreateDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeliveryProposal401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateDeliveryProposal401JSONResponse) VisitCreateDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeliveryProposal403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateDeliveryProposal403JSONResponse) VisitCreateDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeliveryProposal404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateDeliveryProposal404JSONResponse) VisitCreateDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeliveryProposal409JSONResponse struct{ ConflictJSONResponse }

func (response CreateDeliveryProposal409JSONResponse) VisitCreateDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeliveryProposal500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateDeliveryProposal500JSONResponse) VisitCreateDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AcceptDeliveryProposalRequestObject struct {
	Id Id `json:"id"`
}

type AcceptDeliveryProposalResponseObject interface {
	VisitAcceptDeliveryProposalResponse(w http.ResponseWriter) error
}

type AcceptDeliveryProposal200JSONResponse DeliveryProposalAcceptResponse

func (response AcceptDeliveryProposal200JSONResponse) VisitAcceptDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AcceptDeliveryProposal401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AcceptDeliveryProposal401JSONResponse) VisitAcceptDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AcceptDeliveryProposal403JSONResponse struct{ ForbiddenJSONResponse }

func (response AcceptDeliveryProposal403JSONResponse) VisitAcceptDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type AcceptDeliveryProposal404JSONResponse struct{ NotFoundJSONResponse }

func (response AcceptDeliveryProposal404JSONResponse) VisitAcceptDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AcceptDeliveryProposal409JSONResponse struct{ ConflictJSONResponse }

func (response AcceptDeliveryProposal409JSONResponse) VisitAcceptDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type AcceptDeliveryProposal500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response AcceptDeliveryProposal500JSONResponse) VisitAcceptDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RejectDeliveryProposalRequestObject struct {
	Id Id `json:"id"`
}

type RejectDeliveryProposalResponseObject interface {
	VisitRejectDeliveryProposalResponse(w http.ResponseWriter) error
}

type RejectDeliveryProposal200JSONResponse DeliveryProposal

func (response RejectDeliveryProposal200JSONResponse) VisitRejectDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RejectDeliveryProposal401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RejectDeliveryProposal401JSONResponse) VisitRejectDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RejectDeliveryProposal403JSONResponse struct{ ForbiddenJSONResponse }

func (response RejectDeliveryProposal403JSONResponse) VisitRejectDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RejectDeliveryProposal404JSONResponse struct{ NotFoundJSONResponse }

func (response RejectDeliveryProposal404JSONResponse) VisitRejectDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RejectDeliveryProposal409JSONResponse struct{ ConflictJSONResponse }

func (response RejectDeliveryProposal409JSONResponse) VisitRejectDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RejectDeliveryProposal500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response RejectDeliveryProposal500JSONResponse) VisitRejectDeliveryProposalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListDonationsRequestObject struct {
	Params ListDonationsParams
}

type ListDonationsResponseObject interface {
	VisitListDonationsResponse(w http.ResponseWriter) error
}

type ListDonations200JSONResponse DonationListResponse

func (response ListDonations200JSONResponse) VisitListDonationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListDonations400JSONResponse struct{ BadRequestJSONResponse }

func (response ListDonations400JSONResponse) VisitListDonationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListDonations401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListDonations401JSONResponse) VisitListDonationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListDonations500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListDonations500JSONResponse) VisitListDonationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateDonationRequestObject struct {
	Body *CreateDonationJSONRequestBody
}

type CreateDonationResponseObject interface {
	VisitCreateDonationResponse(w http.ResponseWriter) error
}

type CreateDonation201JSONResponse Donation

func (response CreateDonation201JSONResponse) VisitCreateDonationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDonation400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateDonation400JSONResponse) VisitCreateDonationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDonation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateDonation401JSONResponse) VisitCreateDonationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateDonation403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateDonation403JSONResponse) VisitCreateDonationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateDonation500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateDonation500JSONResponse) VisitCreateDonationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationRequestObject struct {
	Id Id `json:"id"`
}

type GetDonationResponseObject interface {
	VisitGetDonationResponse(w http.ResponseWriter) error
}

type GetDonation200JSONResponse Donation

func (response GetDonation200JSONResponse) VisitGetDonationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDonation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetDonation401JSONResponse) VisitGetDonationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetDonation404JSONResponse struct{ NotFoundJSONResponse }

func (response GetDonation404JSONResponse) VisitGetDonationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDonation500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetDonation500JSONResponse) VisitGetDonationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetMe500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetMe500JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMyProfileRequestObject struct {
}

type GetMyProfileResponseObject interface {
	VisitGetMyProfileResponse(w http.ResponseWriter) error
}

type GetMyProfile200JSONResponse Profile

func (response GetMyProfile200JSONResponse) VisitGetMyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMyProfile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMyProfile401JSONResponse) VisitGetMyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetMyProfile404JSONResponse struct{ NotFoundJSONResponse }

func (response GetMyProfile404JSONResponse) VisitGetMyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetMyProfile500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetMyProfile500JSONResponse) VisitGetMyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMyProfileRequestObject struct {
	Body *UpdateMyProfileJSONRequestBody
}

type UpdateMyProfileResponseObject interface {
	VisitUpdateMyProfileResponse(w http.ResponseWriter) error
}

type UpdateMyProfile200JSONResponse Profile

func (response UpdateMyProfile200JSONResponse) VisitUpdateMyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMyProfile400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateMyProfile400JSONResponse) VisitUpdateMyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMyProfile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateMyProfile401JSONResponse) VisitUpdateMyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMyProfile500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateMyProfile500JSONResponse) VisitUpdateMyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListNotificationsRequestObject struct {
	Params ListNotificationsParams
}

type ListNotificationsResponseObject interface {
	VisitListNotificationsResponse(w http.ResponseWriter) error
}

type ListNotifications200JSONResponse NotificationListResponse

func (response ListNotifications200JSONResponse) VisitListNotificationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListNotifications400JSONResponse struct{ BadRequestJSONResponse }

func (response ListNotifications400JSONResponse) VisitListNotificationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListNotifications401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListNotifications401JSONResponse) VisitListNotificationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListNotifications500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListNotifications500JSONResponse) VisitListNotificationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type StreamNotificationsRequestObject struct {
}

type StreamNotificationsResponseObject interface {
	VisitStreamNotificationsResponse(w http.ResponseWriter) error
}

type StreamNotifications200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response StreamNotifications200TexteventStreamResponse) VisitStreamNotificationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type StreamNotifications401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StreamNotifications401JSONResponse) VisitStreamNotificationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StreamNotifications500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response StreamNotifications500JSONResponse) VisitStreamNotificationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type MarkNotificationReadRequestObject struct {
	Id Id `json:"id"`
}

type MarkNotificationReadResponseObject interface {
	VisitMarkNotificationReadResponse(w http.ResponseWriter) error
}

type MarkNotificationRead200JSONResponse Notification

func (response MarkNotificationRead200JSONResponse) VisitMarkNotificationReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MarkNotificationRead401JSONResponse struct{ UnauthorizedJSONResponse }

func (response MarkNotificationRead401JSONResponse) VisitMarkNotificationReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type MarkNotificationRead404JSONResponse struct{ NotFoundJSONResponse }

func (response MarkNotificationRead404JSONResponse) VisitMarkNotificationReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MarkNotificationRead500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response MarkNotificationRead500JSONResponse) VisitMarkNotificationReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type MarkPickupDeliveredRequestObject struct {
	Id   Id `json:"id"`
	Body *MarkPickupDeliveredJSONRequestBody
}

type MarkPickupDeliveredResponseObject interface {
	VisitMarkPickupDeliveredResponse(w http.ResponseWriter) error
}

type MarkPickupDelivered200JSONResponse Pickup

func (response MarkPickupDelivered200JSONResponse) VisitMarkPickupDeliveredResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MarkPickupDelivered401JSONResponse struct{ UnauthorizedJSONResponse }

func (response MarkPickupDelivered401JSONResponse) VisitMarkPickupDeliveredResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type MarkPickupDelivered403JSONResponse struct{ ForbiddenJSONResponse }

func (response MarkPickupDelivered403JSONResponse) VisitMarkPickupDeliveredResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type MarkPickupDelivered404JSONResponse struct{ NotFoundJSONResponse }

func (response MarkPickupDelivered404JSONResponse) VisitMarkPickupDeliveredResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MarkPickupDelivered409JSONResponse struct{ ConflictJSONResponse }

func (response MarkPickupDelivered409JSONResponse) VisitMarkPickupDeliveredResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type MarkPickupDelivered500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response MarkPickupDelivered500JSONResponse) VisitMarkPickupDeliveredResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type MarkPickupPickedUpRequestObject struct {
	Id   Id `json:"id"`
	Body *MarkPickupPickedUpJSONRequestBody
}

type MarkPickupPickedUpResponseObject interface {
	VisitMarkPickupPickedUpResponse(w http.ResponseWriter) error
}

type MarkPickupPickedUp200JSONResponse Pickup

func (response MarkPickupPickedUp200JSONResponse) VisitMarkPickupPickedUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MarkPickupPickedUp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response MarkPickupPickedUp401JSONResponse) VisitMarkPickupPickedUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type MarkPickupPickedUp403JSONResponse struct{ ForbiddenJSONResponse }

func (response MarkPickupPickedUp403JSONResponse) VisitMarkPickupPickedUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type MarkPickupPickedUp404JSONResponse struct{ NotFoundJSONResponse }

func (response MarkPickupPickedUp404JSONResponse) VisitMarkPickupPickedUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MarkPickupPickedUp409JSONResponse struct{ ConflictJSONResponse }

func (response MarkPickupPickedUp409JSONResponse) VisitMarkPickupPickedUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type MarkPickupPickedUp500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response MarkPickupPickedUp500JSONResponse) VisitMarkPickupPickedUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListReceiversRequestObject struct {
	Params ListReceiversParams
}

type ListReceiversResponseObject interface {
	VisitListReceiversResponse(w http.ResponseWriter) error
}

type ListReceivers200JSONResponse ProfileListResponse

func (response ListReceivers200JSONResponse) VisitListReceiversResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListReceivers400JSONResponse struct{ BadRequestJSONResponse }

func (response ListReceivers400JSONResponse) VisitListReceiversResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListReceivers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListReceivers401JSONResponse) VisitListReceiversResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListReceivers403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListReceivers403JSONResponse) VisitListReceiversResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListReceivers500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListReceivers500JSONResponse) VisitListReceiversResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Log in as a seeded demo user.
	// (POST /auth/demo-login)
	DemoLogin(ctx context.Context, request DemoLoginRequestObject) (DemoLoginResponseObject, error)
	// List delivery proposals visible to current role.
	// (GET /delivery-proposals)
	ListDeliveryProposals(ctx context.Context, request ListDeliveryProposalsRequestObject) (ListDeliveryProposalsResponseObject, error)
	// Create a delivery proposal. Volunteer only.
	// (POST /delivery-proposals)
	CreateDeliveryProposal(ctx context.Context, request CreateDeliveryProposalRequestObject) (CreateDeliveryProposalResponseObject, error)
	// Accept delivery proposal as donor or receiver.
	// (POST /delivery-proposals/{id}/accept)
	AcceptDeliveryProposal(ctx context.Context, request AcceptDeliveryProposalRequestObject) (AcceptDeliveryProposalResponseObject, error)
	// Reject delivery proposal as donor or receiver.
	// (POST /delivery-proposals/{id}/reject)
	RejectDeliveryProposal(ctx context.Context, request RejectDeliveryProposalRequestObject) (RejectDeliveryProposalResponseObject, error)
	// List donations visible to current role.
	// (GET /donations)
	ListDonations(ctx context.Context, request ListDonationsRequestObject) (ListDonationsResponseObject, error)
	// Create a donation. Donor only.
	// (POST /donations)
	CreateDonation(ctx context.Context, request CreateDonationRequestObject) (CreateDonationResponseObject, error)
	// Get donation by ID.
	// (GET /donations/{id})
	GetDonation(ctx context.Context, request GetDonationRequestObject) (GetDonationResponseObject, error)
	// Get current authenticated user.
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Get current user's profile.
	// (GET /me/profile)
	GetMyProfile(ctx context.Context, request GetMyProfileRequestObject) (GetMyProfileResponseObject, error)
	// Update current user's profile.
	// (PUT /me/profile)
	UpdateMyProfile(ctx context.Context, request UpdateMyProfileRequestObject) (UpdateMyProfileResponseObject, error)
	// List notifications.
	// (GET /notifications)
	ListNotifications(ctx context.Context, request ListNotificationsRequestObject) (ListNotificationsResponseObject, error)
	// Stream current notifications as Server-Sent Events.
	// (GET /notifications/stream)
	StreamNotifications(ctx context.Context, request StreamNotificationsRequestObject) (StreamNotificationsResponseObject, error)
	// Mark notification read.
	// (POST /notifications/{id}/read)
	MarkNotificationRead(ctx context.Context, request MarkNotificationReadRequestObject) (MarkNotificationReadResponseObject, error)
	// Mark pickup as delivered. Assigned volunteer only.
	// (POST /pickups/{id}/deliver)
	MarkPickupDelivered(ctx context.Context, request MarkPickupDeliveredRequestObject) (MarkPickupDeliveredResponseObject, error)
	// Mark pickup as picked up. Assigned volunteer only.
	// (POST /pickups/{id}/pickup)
	MarkPickupPickedUp(ctx context.Context, request MarkPickupPickedUpRequestObject) (MarkPickupPickedUpResponseObject, error)
	// List receiver profiles. Volunteer only.
	// (GET /receivers)
	ListReceivers(ctx context.Context, request ListReceiversRequestObject) (ListReceiversResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DemoLogin operation middleware
func (sh *strictHandler) DemoLogin(w http.ResponseWriter, r *http.Request) {
	var request DemoLoginRequestObject

	var body DemoLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DemoLogin(ctx, request.(DemoLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DemoLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DemoLoginResponseObject); ok {
		if err := validResponse.VisitDemoLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDeliveryProposals operation middleware
func (sh *strictHandler) ListDeliveryProposals(w http.ResponseWriter, r *http.Request, params ListDeliveryProposalsParams) {
	var request ListDeliveryProposalsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDeliveryProposals(ctx, request.(ListDeliveryProposalsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDeliveryProposals")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDeliveryProposalsResponseObject); ok {
		if err := validResponse.VisitListDeliveryProposalsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDeliveryProposal operation middleware
func (sh *strictHandler) CreateDeliveryProposal(w http.ResponseWriter, r *http.Request) {
	var request CreateDeliveryProposalRequestObject

	var body CreateDeliveryProposalJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDeliveryProposal(ctx, request.(CreateDeliveryProposalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDeliveryProposal")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDeliveryProposalResponseObject); ok {
		if err := validResponse.VisitCreateDeliveryProposalResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AcceptDeliveryProposal operation middleware
func (sh *strictHandler) AcceptDeliveryProposal(w http.ResponseWriter, r *http.Request, id Id) {
	var request AcceptDeliveryProposalRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AcceptDeliveryProposal(ctx, request.(AcceptDeliveryProposalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AcceptDeliveryProposal")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AcceptDeliveryProposalResponseObject); ok {
		if err := validResponse.VisitAcceptDeliveryProposalResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RejectDeliveryProposal operation middleware
func (sh *strictHandler) RejectDeliveryProposal(w http.ResponseWriter, r *http.Request, id Id) {
	var request RejectDeliveryProposalRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RejectDeliveryProposal(ctx, request.(RejectDeliveryProposalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RejectDeliveryProposal")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RejectDeliveryProposalResponseObject); ok {
		if err := validResponse.VisitRejectDeliveryProposalResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDonations operation middleware
func (sh *strictHandler) ListDonations(w http.ResponseWriter, r *http.Request, params ListDonationsParams) {
	var request ListDonationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDonations(ctx, request.(ListDonationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDonations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDonationsResponseObject); ok {
		if err := validResponse.VisitListDonationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDonation operation middleware
func (sh *strictHandler) CreateDonation(w http.ResponseWriter, r *http.Request) {
	var request CreateDonationRequestObject

	var body CreateDonationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDonation(ctx, request.(CreateDonationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDonation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDonationResponseObject); ok {
		if err := validResponse.VisitCreateDonationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDonation operation middleware
func (sh *strictHandler) GetDonation(w http.ResponseWriter, r *http.Request, id Id) {
	var request GetDonationRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDonation(ctx, request.(GetDonationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDonation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDonationResponseObject); ok {
		if err := validResponse.VisitGetDonationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyProfile operation middleware
func (sh *strictHandler) GetMyProfile(w http.ResponseWriter, r *http.Request) {
	var request GetMyProfileRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyProfile(ctx, request.(GetMyProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyProfile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMyProfileResponseObject); ok {
		if err := validResponse.VisitGetMyProfileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMyProfile operation middleware
func (sh *strictHandler) UpdateMyProfile(w http.ResponseWriter, r *http.Request) {
	var request UpdateMyProfileRequestObject

	var body UpdateMyProfileJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMyProfile(ctx, request.(UpdateMyProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMyProfile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMyProfileResponseObject); ok {
		if err := validResponse.VisitUpdateMyProfileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListNotifications operation middleware
func (sh *strictHandler) ListNotifications(w http.ResponseWriter, r *http.Request, params ListNotificationsParams) {
	var request ListNotificationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListNotifications(ctx, request.(ListNotificationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNotifications")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListNotificationsResponseObject); ok {
		if err := validResponse.VisitListNotificationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamNotifications operation middleware
func (sh *strictHandler) StreamNotifications(w http.ResponseWriter, r *http.Request) {
	var request StreamNotificationsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StreamNotifications(ctx, request.(StreamNotificationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamNotifications")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StreamNotificationsResponseObject); ok {
		if err := validResponse.VisitStreamNotificationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MarkNotificationRead operation middleware
func (sh *strictHandler) MarkNotificationRead(w http.ResponseWriter, r *http.Request, id Id) {
	var request MarkNotificationReadRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MarkNotificationRead(ctx, request.(MarkNotificationReadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MarkNotificationRead")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MarkNotificationReadResponseObject); ok {
		if err := validResponse.VisitMarkNotificationReadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MarkPickupDelivered operation middleware
func (sh *strictHandler) MarkPickupDelivered(w http.ResponseWriter, r *http.Request, id Id) {
	var request MarkPickupDeliveredRequestObject

	request.Id = id

	var body MarkPickupDeliveredJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MarkPickupDelivered(ctx, request.(MarkPickupDeliveredRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MarkPickupDelivered")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MarkPickupDeliveredResponseObject); ok {
		if err := validResponse.VisitMarkPickupDeliveredResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MarkPickupPickedUp operation middleware
func (sh *strictHandler) MarkPickupPickedUp(w http.ResponseWriter, r *http.Request, id Id) {
	var request MarkPickupPickedUpRequestObject

	request.Id = id

	var body MarkPickupPickedUpJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MarkPickupPickedUp(ctx, request.(MarkPickupPickedUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MarkPickupPickedUp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MarkPickupPickedUpResponseObject); ok {
		if err := validResponse.VisitMarkPickupPickedUpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListReceivers operation middleware
func (sh *strictHandler) ListReceivers(w http.ResponseWriter, r *http.Request, params ListReceiversParams) {
	var request ListReceiversRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListReceivers(ctx, request.(ListReceiversRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListReceivers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListReceiversResponseObject); ok {
		if err := validResponse.VisitListReceiversResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
