apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foodlink
resources:
  - namespace.yaml
  - postgresql.yaml
  - api.yaml
  - ingress.yaml
  - networkpolicy.yaml
images:
  - name: ghcr.io/christolx/foodlink-api
    newTag: sha-c3b396d
